spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      maximum-pool-size: 50 #커넥션 풀 갯수 설정
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:test #;MODE=MySQL #- mysql문법으로 변경하는 설버
    driver-class-name: org.h2.Driver
  jpa:
#    open-in-view: false
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #- mysql문법으로 변경하는 설정
        format_sql: true # 쿼리를 가독성있게 바꿔줌
    show-sql: true      # SQL 쿼리 출력
    defer-datasource-initialization: true
  profiles:
    include: oauth
  sql:
    init:
      data-locations: classpath*:db/data.sql
  # 이미지 파일 용량 제한 수정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
server:
  servlet:
    encoding:
      charset: UTF-8

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug # 커넥션 풀 로그
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace # sql에 들어가는 값 로그